# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import neo

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(418, 285)
        self.login_btn = QtWidgets.QPushButton(Form)
        self.login_btn.setGeometry(QtCore.QRect(260, 90, 75, 71))
        self.login_btn.setObjectName("login_btn")
        self.title = QtWidgets.QLabel(Form)
        self.title.setGeometry(QtCore.QRect(20, 10, 381, 71))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(130, 180, 121, 91))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/neo/neoable.png"))
        self.label_4.setWordWrap(False)
        self.label_4.setObjectName("label_4")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(70, 88, 58, 81))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(140, 87, 111, 81))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.id = QtWidgets.QLineEdit(self.layoutWidget1)
        self.id.setObjectName("id")
        self.verticalLayout_2.addWidget(self.id)
        self.psw = QtWidgets.QLineEdit(self.layoutWidget1)
        self.psw.setObjectName("psw")
        self.verticalLayout_2.addWidget(self.psw)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "에어매트 테스트 시스템 로그인"))
        self.login_btn.setText(_translate("Form", "로그인"))
        self.title.setText(_translate("Form", "에어매트 테스트 시스템\n"
"(Airmat Test System)"))
        self.label.setText(_translate("Form", "아이디 :"))
        self.label_2.setText(_translate("Form", "비밀번호 :"))

