# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import airmat_menu

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 540)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBar.sizePolicy().hasHeightForWidth())
        self.toolBar.setSizePolicy(sizePolicy)
        self.toolBar.setStyleSheet("QToolButton{spacing:20px;}")
        self.toolBar.setIconSize(QtCore.QSize(30, 30))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionvisual = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/menu/visual.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionvisual.setIcon(icon)
        self.actionvisual.setObjectName("actionvisual")
        self.actionconnect_serial = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/menu/connect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionconnect_serial.setIcon(icon1)
        self.actionconnect_serial.setObjectName("actionconnect_serial")
        self.actionsetting = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/menu/setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionsetting.setIcon(icon2)
        self.actionsetting.setObjectName("actionsetting")
        self.toolBar.addAction(self.actionvisual)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionconnect_serial)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionsetting)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "공압 매트 시각화 프로그램"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionvisual.setText(_translate("MainWindow", "visual"))
        self.actionvisual.setToolTip(_translate("MainWindow", "공압값 시각화"))
        self.actionconnect_serial.setText(_translate("MainWindow", "connect_serial"))
        self.actionconnect_serial.setToolTip(_translate("MainWindow", "포트연결"))
        self.actionsetting.setText(_translate("MainWindow", "setting"))
